{
 "title": "Clash Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Version Info",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "clash_version_info",
     "legendFormat": "Version: {{version}}, Premium: {{premium}}"
    }
   ]
  },
  {
   "title": "Up status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "clash_up" }
   ]
  },
  {
   "title": "Download Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(clash_connection_download_total[100y]))",
     "legendFormat": "Download Total"
    }
   ]
  },
  {
   "title": "Download Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(clash_connection_upload_total[100y]))",
     "legendFormat": "Upload Total"
    }
   ]
  },
  {
   "title": "Proxy Delay",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ms", "label": "Delay" }
   ],
   "targets": [
    { "expr": "clash_proxy_delay", "legendFormat": "{{provider}}:{{name}}" }
   ]
  },
  {
   "title": "Traffic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(clash_connection_download_total[5m]))",
     "legendFormat": "Download"
    },
    {
     "expr": "sum(irate(clash_connection_upload_total[5m]))",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}